services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/htdocs
    command: >
      bash -c "a2enmod rewrite && sed -ri -e 's!/var/www/html!/var/www/html/htdocs!g' /etc/apache2/sites-available/*.conf && sed -ri -e 's!/var/www/!/var/www/html/htdocs!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf && docker-php-ext-install mysqli pdo_mysql && apache2-foreground"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto_dual
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  # gather-sync:
  #   build: ./htdocs/gather-sync
  #   depends_on:
  #     - db
  #   environment:
  #     GATHER_API_KEY: SeyptHJjcOc54qsL
  #     GATHER_SPACE_ID: oxMKxoJO51E/Oficina
  #     DB_HOST: db
  #     DB_USER: root
  #     DB_PASS: root
  #     DB_NAME: proyecto_dual

volumes:
  db_data:
